## @param resources.requests.cpu The requested cpu for containers
## @param resources.requests.memory The requested memory for containers
## @param resources.limits.cpu The cpu limits for containers
## @param resources.limits.memory The memory limits for containers
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

## @param .Values.containerPorts[] Set necessary ports parameters
## @param .Values.serviceType Set specified service type
serviceType: ClusterIP
containerPorts:
  - name: http
    internalPort: 80
    externalPort: 8080
    protocol: TCP

## @param .Values.ingress[] Configure ingress parameters
ingress:
  rules:
    - ingressPath: /
      servicePort: http

startupProbe:
  enabled: true
  path: /healthz/startup
  port: 8080
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 5

## @param .Values.livenessProbe.enabled Enable livenessProbe
## @param .Values.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
## @param .Values.livenessProbe.periodSeconds Period seconds for livenessProbe
## @param .Values.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
## @param .Values.livenessProbe.failureThreshold Failure threshold for livenessProbe
## @param .Values.livenessProbe.successThreshold Success threshold for livenessProbe
livenessProbe:
  enabled: true
  path: /healthz/alive
  port: 8080
  scheme: HTTP
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

## @param .Values.readinessProbe.enabled Enable readinessProbe
## @param .Values.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
## @param .Values.readinessProbe.periodSeconds Period seconds for readinessProbe
## @param .Values.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
## @param .Values.readinessProbe.failureThreshold Failure threshold for readinessProbe
## @param .Values.readinessProbe.successThreshold Success threshold for readinessProbe
##
readinessProbe:
  enabled: true
  path: /healthz/ready
  port: 8080
  scheme: HTTP
  timeoutSeconds: 1
  successThreshold: 3
